# Generated by Django 6.1.1 on 2026-09-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="subject",
            new_name="phone",
        ),
    ]
